@startuml{Androidが最適なリソースを見つける仕組み.png}

title Androidが最適なリソースを見つける仕組み


start

:デバイスの設定を取得する;

if (取得したデバイスの設定を満たさないことが明らかであるか？) then (Yes)
    note right
        例えば、デバイスの言語設定が "日本語" であり、
        リソースの対象言語が "英語" である場合は
        "Yes" を選択する。
    end note
    :対象のリソースを除外する;
else (No)
    ' do nothing.
endif

repeat
    repeat

        :リソース修飾子の優先順位表を確認する;
        :次に優先順位の高いリソースを確認する;

    repeat while (該当の修飾子に関する指定がされたディレクトリが存在しない)

    :その修飾子に関する指定がされていないディレクトリを除外する;

    note right
        画面ピクセル密度は例外とのこと。（要調査）
    end note
repeat while (残るリソースディレクトリが二つ以上ある)

:残った一つのディレクトリに存在するリソースが適用される;

stop


@enduml